version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_JDBC_URL=jdbc:mysql://mysql:3306/jjim?serverTimezone=UTC&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=12341234
    networks:
      - app-network

  mysql:
    image: mysql:8.0.41
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12341234
      MYSQL_DATABASE: jjim
    ports:
      - "33306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
