server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/jjim?serverTimezone=UTC&useSSL=false
    username: root
    password: 12341234
  sql:
    init:
      mode: always
      data-locations: 'classpath:dml.sql'
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create-drop

